const menu = [
    {
      id : 1,
      title : 'Plain Dosa',
      category : 'dosa',
      price : 90,
      img : './images/item-1.jpeg',
      desc : `Served with sambhar, 2 chutney, coconut and tomato`,
  },
  {
    id : 2,
    title : 'Mysore Masala Dosa',
    category : 'dosa',
    price : 130,
    img : './images/item-2.jpeg',
    desc : `Mysore masala dosa is crispy and soft dosa spiced with red chutney and served with A potato dish, served with sambhar and chutney`,
  },
  {
    id : 3,
    title : 'Masala Dosa',
    category : 'dosa',
    price : 120,
    img : './images/item-3.jpeg',
    desc : `Roasted and crispy dosa. Served with coconut chutney`,
  },
  {
    id : 4,
    title : 'Aloo Paratha Combo',
    category : 'combo',
    price : 50,
    img : './images/item-4.jpeg',
    desc: `2 AlooParatha + Green Chutney + Sauce + Achar + Dahi`,
  },
  {
    id : 5,
    title : 'Gobhi Paratha Combo',
    category : 'combo',
    price : 55,
    img : './images/item-5.jpeg',
    desc:`2 GobhiParatha + Green Chutney + Sauce + Achar + Dahi`,
  },
  {
    id : 6,
    title : 'Paneer Stuffed Paratha Combo',
    category : 'combo',
    price : 60,
    img : './images/item-6.jpeg',
    desc:`2 Paneer Stuffed Paratha + Green Chutney + Sauce + Achar + Dahi`,
  }, 
  {
    id : 7,
    title : 'Onion Paratha Combo',
    category : 'combo',
    price :35,
    img : './images/item-7.jpeg',
    desc:`2 Onion Paratha + Green Chutney + Sauce + Achar + Dahi`,
  },
  {
    id : 8,
    title : 'Sada Dosa',
    category : 'dosa',
    price :104,
    img : './images/item-8.webp',
    desc:`Sada dosa is a plain typically served with chutneys and sambar`,
},
{
  id : 9,
  title : 'Paneer Dosa',
  category : 'dosa',
  price :189,
  img : './images/item-9.jpeg',
  desc:`Stuffed with a spiced mixture of paneer often accompanied by chutneys and sambar`,
},
{
  id : 10,
  title : 'Mysore Masala Dosa',
  category : 'dosa',
  price :171,
  img : './images/item-10.jpeg',
  desc:`Spread with a red chili chutney and filled with a tangy, spiced potato mixture`,
},
{
  id : 11,
  title : 'Rava Masala Dosa',
  category : 'dosa',
  price :171,
  img : './images/item-11.jpeg',
  desc:`Filled with a spiced potato mixture, and typically served with chutneys and sambar`,
},
{
  id : 12,
  title : 'Plain Rava Dosa',
  category : 'dosa',
  price :116,
  img : './images/item-12.jpeg',
  desc:`Plain rava dosa is a crispy seasoned with spices`,
},
{
  id : 13,
  title : 'Mysore Sada Dosa',
  category : 'dosa',
  price :122,
  img : './images/item-13.jpeg',
  desc:`Mysore sada dosa is a spicy, crisp rice and lentil crepe layered with a flavorful red chutney`,
},
{
  id : 14,
  title : 'Noodles Dosa',
  category : 'dosa',
  price :183,
  img : './images/item-14.jpeg',
  desc:`Crispy dosa with stir-fried noodles and vegetables for a unique twist`,
},
{
  id : 15,
  title : 'Cheese Masala Dosa',
  category : 'dosa',
  price :220,
  img : './images/item-15.jpeg',
  desc:`Stuffed dosa filled with a spiced potato filling and melted cheese for an indulgent twist`,
},
{
  id : 16,
  title : 'Cheese Cut Dosa',
  category : 'dosa',
  price :142.86,
  img : './images/item-16.jpeg',
  desc:`Cut into pieces and often served with chutneys and sambar`,
},
{
  id : 17,
  title : 'Ginnie Dosa',
  category : 'dosa',
  price :171.43,
  img : './images/item-17.jpeg',
  desc:`Ginnie dosa is a mini, crispy dosa often served in a stack or rolled, typically with a variety of chutneys and sambar`,
},
{
  id : 18,
  title : 'Paneer Cut Dosa',
  category : 'dosa',
  price :142.86,
  img : './images/item-18.jpeg',
  desc:`Spiced paneer chunks, cut into pieces, and usually accompanied by chutneys and sambar`,
},
{
  id : 19,
  title : 'Paneer Tikka Dosa',
  category : 'dosa',
  price :171.43,
  img : './images/item-19.jpeg',
  desc:`Combines a crispy dosa with a flavorful filling of spiced paneer tikka usually accompanied by chutneys and sambar`,
},
{
  id : 20,
  title : 'Paper Dosa',
  category : 'dosa',
  price :123.81,
  img : './images/item-20.jpeg',
  desc:`Paper dosa is an ultra-thin, crisp dosa that is rolled into a large, delicate sheet, offering a light and crunchy texture`,
},
{
  id : 21,
  title : 'Butter Cheese Onion Masala Dosa',
  category : 'dosa',
  price :160,
  img : './images/item-21.jpeg',
  desc:`Stuffed with a spiced potato filling, topped with sautéed onions and melted cheese, and enriched with a generous layer of butter`,
},
{
  id : 22,
  title : 'Idli Sambar',
  category : 'idli',
  price :150,
  img : './images/item-22.jpeg',
  desc:`Steamed rice cakes (idlis) served with a flavorful, spicy lentil and vegetable stew (sambar)`,
},
{
  id : 23,
  title : 'Fried idli',
  category : 'idli',
  price :90,
  img : './images/item-23.jpeg',
  desc:`Leftover steamed idlis cut into pieces, seasoned, and pan-fried until crispy, often garnished with spices and herbs`,
},
{
  id : 24,
  title : 'Peri Peri Fried Idli',
  category : 'idli',
  price :114.29,
  img : './images/item-24.jpeg',
  desc:`Pan-fried idli pieces tossed in a zesty peri peri seasoning, adding a spicy and tangy twist`,
},
{
  id : 25,
  title : 'Plain Idli',
  category : 'idli',
  price :85.71,
  img : './images/item-25.jpeg',
  desc:`Accompaniment to sambar and chutneys`,
},
{
  id : 26,
  title : 'Masala Idli',
  category : 'idli',
  price :90,
  img : './images/item-26.jpeg',
  desc:`Steamed idli pieces stir-fried with aromatic spices, curry leaves, and vegetables`,
},
{
  id : 27,
  title : 'Ghee Idli',
  category : 'idli',
  price :100,
  img : './images/item-27.jpeg',
  desc:`Steamed idli generously drizzled with clarified butter (ghee)`,
},
{
  id : 28,
  title : 'Poori Sabji',
  category : 'Poori',
  price :140,
  img : './images/item-28.jpeg',
  desc:`Deep-fried bread (poori) served with a spiced vegetable curry (sabji)`,
},
{
    id : 29,
    title : 'Poori Chole',
    category : 'Poori',
    price :151,
    img : './images/item-29.jpeg',
    desc:`Deep-fried bread (poori) paired with a spicy, tangy chickpea curry (chole)`,
},
{
  id : 30,
  title : 'Poori',
  category : 'Poori',
  price :28,
  img : './images/item-30.jpeg',
  desc:`Deep-fried Indian bread that is soft, puffed, and golden brown`,
},
{
  id : 31,
  title : 'Poori With Boondi wali Kadhi',
  category : 'Poori',
  price :175,
  img : './images/item-31.jpeg',
  desc:`Deep-fried bread (poori) served with a tangy yogurt-based curry enriched with crispy boondi`,
},
{
  id : 32,
  title : 'Aloo Mashala Poori with Aloo Sabji',
  category : 'Poori',
  price :135,
  img : './images/item-32.jpg',
  desc:`Deep-fried bread (poori) and a hearty potato curry (aloo sabji)`,
},
{
  id : 33,
  title : 'Besan Masala Poori',
  category : 'Poori',
  price :115,
  img : './images/item-33.jpeg',
  desc:`Spiced deep-fried bread with besan and traditional spices, paired with lemon pickle.`,
},
{
  id : 34,
  title : 'Sweet Poori with Nimbu ka Achar',
  category : 'Poori',
  price :125,
  img : './images/item-34.jpeg',
  desc:`Sweet deep-fried bread paired with tangy lemon pickle`,
},
{
  id : 35,
  title : 'Tawa Roti',
  category : 'Roti',
  price :22,
  img : './images/item-35.jpeg',
  desc:`Heated griddle called a tawa, resulting in a soft and slightly crispy texture`,
},
{
  id : 36,
  title : 'Butter Tawa Roti',
  category : 'Roti',
  price :31,
  img : './images/item-36.jpeg',
  desc:`Indian flatbread cooked on a griddle and generously brushed with melted butter for a rich, savory taste`,
},
{
  id : 37,
  title : 'Shahi Paneer With Roti',
  category : 'Roti',
  price :189,
  img : './images/item-37.jpeg',
  desc:`Shahi Paneer 250 Ml + 4 Butter Tawa Roti`,
},
{
  id : 38,
  title : 'Plain Tawa Roti',
  category : 'Roti',
  price :15,
  img : './images/item-38.jpeg',
  desc:`Soft texture and mild flavor`,
},
{
  id : 39,
  title : 'Makki ki Roti',
  category : 'Roti',
  price :39,
  img : './images/item-39.jpeg',
  desc:`Indian flatbread made from cornmeal, known for its hearty texture and distinctive, slightly nutty flavor`,
},
{
  id : 40,
  title : 'Missi Roti',
  category : 'Roti',
  price :40,
  img : './images/item-40.jpeg',
  desc:`Indian flatbread made from a blend of wheat and gram flour, infused with aromatic herbs and spices for added flavor`,
},
{
  id : 41,
  title : 'Plain Tandoori Roti',
  category : 'Roti',
  price :15,
  img : './images/item-41.jpeg',
  desc:`Indian flatbread baked in a tandoor oven, resulting in a crisp, slightly charred exterior and soft interior`,
},
{
  id : 42,
  title : 'Vada Sambar',
  category : 'Vada',
  price :61,
  img : './images/item-42.jpeg',
  desc:`Savory lentil doughnuts (vada) served with a spicy, tangy lentil soup (sambar)`,
},
{
  id : 43,
  title : 'Dahi Vada',
  category : 'Vada',
  price :79,
  img : './images/item-43.jpeg',
  desc:`Indian snack featuring soft, fried lentil dumplings soaked in yogurt and topped with spices and chutneys`,
},
{
  id : 44,
  title : 'Sweet Dahi Vada',
  category : 'Vada',
  price :135,
  img : './images/item-44.jpeg',
  desc:`Spongy lentil dumpling soaked in creamy yogurt, drizzled with sweet tamarind chutney and spices`,
},
{
  id : 45,
  title : 'Vada',
  category : 'Vada',
  price :15,
  img : './images/item-45.jpeg',
  desc:`Moong dal vada`,
},
{
  id : 46,
  title : 'Sabudana Vada',
  category : 'Vada',
  price :70,
  img : './images/item-46.jpeg',
  desc:`Sabudana vada is a crispy, spiced fritter made from tapioca pearls, potatoes, and peanuts, often enjoyed as a savory snack`,
},
{
  id : 47,
  title : 'Uttapam',
  category : 'Uttapam',
  price :130,
  img : './images/item-47.jpeg',
  desc:`South Indian pancake topped with vegetables and spices`,
},
{
  id : 48,
  title : 'Masala Uttapam',
  category : 'Uttapam',
  price :160,
  img : './images/item-48.jpeg',
  desc:`Topping of sautéed onions, tomatoes, and green chilies for extra flavor`,
},
{
  id : 49,
  title : 'Butter Uttapam',
  category : 'Uttapam',
  price :160,
  img : './images/item-49.jpeg',
  desc:`South Indian pancake cooked with a generous amount of butter, enhancing its flavor and crispiness`,
},
{
  id : 50,
  title : 'Cheese Uttapam',
  category : 'Uttapam',
  price :160,
  img : './images/item-50.jpeg',
  desc:`Uttapam topped with melted cheese, adding a creamy and savory twist`,
},
{
  id : 51,
  title : 'Schezwan Uttapam',
  category : 'Uttapam',
  price :160,
  img : './images/item-51.jpeg',
  desc:`Schezwan sauce for a flavorful, Indo-Chinese twist`,
},
{
  id : 52,
  title : 'Butter Cheese Uttapam',
  category : 'Uttapam',
  price :180,
  img : './images/item-52.jpeg',
  desc:`Savory pancake topped with a blend of melted cheese and butter, offering a creamy and indulgent twist`,
},
{
  id : 53,
  title : 'Cheese Masala Uttapam',
  category : 'Uttapam',
  price :180,
  img : './images/item-53.jpeg',
  desc:`Pancake topped with a blend of spicy vegetables and melted cheese, combining traditional and cheesy elements`,
},
{
  id : 54,
  title : 'Upma',
  category : 'Upma',
  price :80,
  img : './images/item-54.jpeg',
  desc:`Semolina cooked with spices, vegetables, and often garnished with herbs`,
},
{
  id : 55,
  title : 'Matar Upma',
  category : 'Upma',
  price :80,
  img : './images/item-55.jpeg',
  desc:`Unique flavor from the addition of tamarind and distinctive spices`,
},
{
  id : 56,
  title : 'Vegetable Upma',
  category : 'Upma',
  price :80,
  img : './images/item-56.jpeg',
  desc:`Mixed with a variety of vegetables, seasoned with spices and herbs`,
},
{
  id : 57,
  title : 'Corn Upma',
  category : 'Upma',
  price :90,
  img : './images/item-57.jpeg',
  desc:`Upma made with sweet corn kernels, semolina, and a blend of spices and herbs`,
},
{
  id : 58,
  title : 'Healthy Oats Upma',
  category : 'Upma',
  price :159,
  img : './images/item-58.jpeg',
  desc:`Cooked with olive oil and pink salt. Use premium quality herbs and English veggies`,
},
{
  id : 59,
  title : 'Coconut Upma',
  category : 'Upma',
  price :110,
  img : './images/item-59.jpeg',
  desc:`Semolina is cooked with grated coconut, spices, and often garnished with fresh herbs`,
},



];
export default menu;