const menu = [
    {
      id : 1,
      title : 'Plain Dosa',
      category : 'dosa',
      price : 90,
      img : './images/item-1.jpeg',
      desc : `Served with sambhar, 2 chutney, coconut and tomato`,
  },
  {
    id : 2,
    title : 'Mysore Masala Dosa',
    category : 'dosa',
    price : 130,
    img : './images/item-2.jpeg',
    desc : `Mysore masala dosa is crispy and soft dosa spiced with red chutney and served with A potato dish, served with sambhar and chutney`,
  },
  {
    id : 3,
    title : 'Masala Dosa',
    category : 'dosa',
    price : 120,
    img : './images/item-3.jpeg',
    desc : `Roasted and crispy dosa. Served with coconut chutney`,
  },
  {
    id : 4,
    title : 'Aloo Paratha Combo',
    category : 'combo',
    price : 50,
    img : './images/item-4.jpeg',
    desc: `2 AlooParatha + Green Chutney + Sauce + Achar + Dahi`,
  },
  {
    id : 5,
    title : 'Gobhi Paratha Combo',
    category : 'combo',
    price : 55,
    img : './images/item-5.jpeg',
    desc:`2 GobhiParatha + Green Chutney + Sauce + Achar + Dahi`,
  },
  {
    id : 6,
    title : 'Paneer Stuffed Paratha Combo',
    category : 'combo',
    price : 60,
    img : './images/item-6.jpeg',
    desc:`2 Paneer Stuffed Paratha + Green Chutney + Sauce + Achar + Dahi`,
  }, 
  {
    id : 7,
    title : 'Onion Paratha Combo',
    category : 'combo',
    price :35,
    img : './images/item-7.jpeg',
    desc:`2 Onion Paratha + Green Chutney + Sauce + Achar + Dahi`,
  },
  {
    id : 8,
    title : 'Sada Dosa',
    category : 'dosa',
    price :104,
    img : './images/item-8.webp',
    desc:`Sada dosa is a plain typically served with chutneys and sambar`,
},
{
  id : 9,
  title : 'Paneer Dosa',
  category : 'dosa',
  price :189,
  img : './images/item-9.jpeg',
  desc:`Stuffed with a spiced mixture of paneer often accompanied by chutneys and sambar`,
},
{
  id : 10,
  title : 'Mysore Masala Dosa',
  category : 'dosa',
  price :171,
  img : './images/item-10.jpeg',
  desc:`Spread with a red chili chutney and filled with a tangy, spiced potato mixture`,
},
{
  id : 11,
  title : 'Rava Masala Dosa',
  category : 'dosa',
  price :171,
  img : './images/item-11.jpeg',
  desc:`Filled with a spiced potato mixture, and typically served with chutneys and sambar`,
},
{
  id : 12,
  title : 'Plain Rava Dosa',
  category : 'dosa',
  price :116,
  img : './images/item-12.jpeg',
  desc:`Plain rava dosa is a crispy seasoned with spices`,
},
{
  id : 13,
  title : 'Mysore Sada Dosa',
  category : 'dosa',
  price :122,
  img : './images/item-13.jpeg',
  desc:`Mysore sada dosa is a spicy, crisp rice and lentil crepe layered with a flavorful red chutney`,
},
{
  id : 14,
  title : 'Noodles Dosa',
  category : 'dosa',
  price :183,
  img : './images/item-14.jpeg',
  desc:`Crispy dosa with stir-fried noodles and vegetables for a unique twist`,
},
{
  id : 15,
  title : 'Cheese Masala Dosa',
  category : 'dosa',
  price :220,
  img : './images/item-15.jpeg',
  desc:`Stuffed dosa filled with a spiced potato filling and melted cheese for an indulgent twist`,
},
{
  id : 16,
  title : 'Cheese Cut Dosa',
  category : 'dosa',
  price :142.86,
  img : './images/item-16.jpeg',
  desc:`Cut into pieces and often served with chutneys and sambar`,
},
{
  id : 17,
  title : 'Ginnie Dosa',
  category : 'dosa',
  price :171.43,
  img : './images/item-17.jpeg',
  desc:`Ginnie dosa is a mini, crispy dosa often served in a stack or rolled, typically with a variety of chutneys and sambar`,
},
{
  id : 18,
  title : 'Paneer Cut Dosa',
  category : 'dosa',
  price :142.86,
  img : './images/item-18.jpeg',
  desc:`Spiced paneer chunks, cut into pieces, and usually accompanied by chutneys and sambar`,
},
{
  id : 19,
  title : 'Paneer Tikka Dosa',
  category : 'dosa',
  price :171.43,
  img : './images/item-19.jpeg',
  desc:`Combines a crispy dosa with a flavorful filling of spiced paneer tikka usually accompanied by chutneys and sambar`,
},
{
  id : 20,
  title : 'Paper Dosa',
  category : 'dosa',
  price :123.81,
  img : './images/item-20.jpeg',
  desc:`Paper dosa is an ultra-thin, crisp dosa that is rolled into a large, delicate sheet, offering a light and crunchy texture`,
},
{
  id : 21,
  title : 'Butter Cheese Onion Masala Dosa',
  category : 'dosa',
  price :160,
  img : './images/item-21.jpeg',
  desc:`Stuffed with a spiced potato filling, topped with sautéed onions and melted cheese, and enriched with a generous layer of butter`,
},
{
  id : 22,
  title : 'Idli Sambar',
  category : 'idli',
  price :150,
  img : './images/item-22.jpeg',
  desc:`Steamed rice cakes (idlis) served with a flavorful, spicy lentil and vegetable stew (sambar)`,
},
{
  id : 23,
  title : 'Fried idli',
  category : 'idli',
  price :90,
  img : './images/item-23.jpeg',
  desc:`Leftover steamed idlis cut into pieces, seasoned, and pan-fried until crispy, often garnished with spices and herbs`,
},
{
  id : 24,
  title : 'Peri Peri Fried Idli',
  category : 'idli',
  price :114.29,
  img : './images/item-24.jpeg',
  desc:`Pan-fried idli pieces tossed in a zesty peri peri seasoning, adding a spicy and tangy twist`,
},
{
  id : 25,
  title : 'Plain Idli',
  category : 'idli',
  price :85.71,
  img : './images/item-25.jpeg',
  desc:`Accompaniment to sambar and chutneys`,
},
{
  id : 26,
  title : 'Masala Idli',
  category : 'idli',
  price :90,
  img : './images/item-26.jpeg',
  desc:`Steamed idli pieces stir-fried with aromatic spices, curry leaves, and vegetables`,
},
{
  id : 27,
  title : 'Ghee Idli',
  category : 'idli',
  price :100,
  img : './images/item-27.jpeg',
  desc:`Steamed idli generously drizzled with clarified butter (ghee)`,
},
{
  id : 28,
  title : 'Poori Sabji',
  category : 'Poori',
  price :140,
  img : './images/item-28.jpeg',
  desc:`Deep-fried bread (poori) served with a spiced vegetable curry (sabji)`,
},
{
    id : 29,
    title : 'Poori Chole',
    category : 'Poori',
    price :151,
    img : './images/item-29.jpeg',
    desc:`Deep-fried bread (poori) paired with a spicy, tangy chickpea curry (chole)`,
},
{
  id : 30,
  title : 'Poori',
  category : 'Poori',
  price :28,
  img : './images/item-30.jpeg',
  desc:`Deep-fried Indian bread that is soft, puffed, and golden brown`,
},
{
  id : 31,
  title : 'Poori With Boondi wali Kadhi',
  category : 'Poori',
  price :175,
  img : './images/item-31.jpeg',
  desc:`Deep-fried bread (poori) served with a tangy yogurt-based curry enriched with crispy boondi`,
},
{
  id : 32,
  title : 'Aloo Mashala Poori with Aloo Sabji',
  category : 'Poori',
  price :135,
  img : './images/item-32.jpg',
  desc:`Deep-fried bread (poori) and a hearty potato curry (aloo sabji)`,
},
{
  id : 33,
  title : 'Besan Masala Poori',
  category : 'Poori',
  price :115,
  img : './images/item-33.jpeg',
  desc:`Spiced deep-fried bread with besan and traditional spices, paired with lemon pickle.`,
},
{
  id : 34,
  title : 'Sweet Poori with Nimbu ka Achar',
  category : 'Poori',
  price :125,
  img : './images/item-34.jpeg',
  desc:`Sweet deep-fried bread paired with tangy lemon pickle`,
},
{
  id : 35,
  title : 'Tawa Roti',
  category : 'Roti',
  price :22,
  img : './images/item-35.jpeg',
  desc:`Heated griddle called a tawa, resulting in a soft and slightly crispy texture`,
},
{
  id : 36,
  title : 'Butter Tawa Roti',
  category : 'Roti',
  price :31,
  img : './images/item-36.jpeg',
  desc:`Indian flatbread cooked on a griddle and generously brushed with melted butter for a rich, savory taste`,
},
{
  id : 37,
  title : 'Shahi Paneer With Roti',
  category : 'Roti',
  price :189,
  img : './images/item-37.jpeg',
  desc:`Shahi Paneer 250 Ml + 4 Butter Tawa Roti`,
},
{
  id : 38,
  title : 'Plain Tawa Roti',
  category : 'Roti',
  price :15,
  img : './images/item-38.jpeg',
  desc:`Soft texture and mild flavor`,
},
{
  id : 39,
  title : 'Makki ki Roti',
  category : 'Roti',
  price :39,
  img : './images/item-39.jpeg',
  desc:`Indian flatbread made from cornmeal, known for its hearty texture and distinctive, slightly nutty flavor`,
},
{
  id : 40,
  title : 'Missi Roti',
  category : 'Roti',
  price :40,
  img : './images/item-40.jpeg',
  desc:`Indian flatbread made from a blend of wheat and gram flour, infused with aromatic herbs and spices for added flavor`,
},
{
  id : 41,
  title : 'Plain Tandoori Roti',
  category : 'Roti',
  price :15,
  img : './images/item-41.jpeg',
  desc:`Indian flatbread baked in a tandoor oven, resulting in a crisp, slightly charred exterior and soft interior`,
},
{
  id : 42,
  title : 'Vada Sambar',
  category : 'Vada',
  price :61,
  img : './images/item-42.jpeg',
  desc:`Savory lentil doughnuts (vada) served with a spicy, tangy lentil soup (sambar)`,
},
{
  id : 43,
  title : 'Dahi Vada',
  category : 'Vada',
  price :79,
  img : './images/item-43.jpeg',
  desc:`Indian snack featuring soft, fried lentil dumplings soaked in yogurt and topped with spices and chutneys`,
},
{
  id : 44,
  title : 'Sweet Dahi Vada',
  category : 'Vada',
  price :135,
  img : './images/item-44.jpeg',
  desc:`Spongy lentil dumpling soaked in creamy yogurt, drizzled with sweet tamarind chutney and spices`,
},
{
  id : 45,
  title : 'Vada',
  category : 'Vada',
  price :15,
  img : './images/item-45.jpeg',
  desc:`Moong dal vada`,
},
{
  id : 46,
  title : 'Sabudana Vada',
  category : 'Vada',
  price :70,
  img : './images/item-46.jpeg',
  desc:`Sabudana vada is a crispy, spiced fritter made from tapioca pearls, potatoes, and peanuts, often enjoyed as a savory snack`,
},
{
  id : 47,
  title : 'Uttapam',
  category : 'Uttapam',
  price :130,
  img : './images/item-47.jpeg',
  desc:`South Indian pancake topped with vegetables and spices`,
},
{
  id : 48,
  title : 'Masala Uttapam',
  category : 'Uttapam',
  price :160,
  img : './images/item-48.jpeg',
  desc:`Topping of sautéed onions, tomatoes, and green chilies for extra flavor`,
},
{
  id : 49,
  title : 'Butter Uttapam',
  category : 'Uttapam',
  price :160,
  img : './images/item-49.jpeg',
  desc:`South Indian pancake cooked with a generous amount of butter, enhancing its flavor and crispiness`,
},
{
  id : 50,
  title : 'Cheese Uttapam',
  category : 'Uttapam',
  price :160,
  img : './images/item-50.jpeg',
  desc:`Uttapam topped with melted cheese, adding a creamy and savory twist`,
},
{
  id : 51,
  title : 'Schezwan Uttapam',
  category : 'Uttapam',
  price :160,
  img : './images/item-51.jpeg',
  desc:`Schezwan sauce for a flavorful, Indo-Chinese twist`,
},
{
  id : 52,
  title : 'Butter Cheese Uttapam',
  category : 'Uttapam',
  price :180,
  img : './images/item-52.jpeg',
  desc:`Savory pancake topped with a blend of melted cheese and butter, offering a creamy and indulgent twist`,
},
{
  id : 53,
  title : 'Cheese Masala Uttapam',
  category : 'Uttapam',
  price :180,
  img : './images/item-53.jpeg',
  desc:`Pancake topped with a blend of spicy vegetables and melted cheese, combining traditional and cheesy elements`,
},
{
  id : 54,
  title : 'Upma',
  category : 'Upma',
  price :80,
  img : './images/item-54.jpeg',
  desc:`Semolina cooked with spices, vegetables, and often garnished with herbs`,
},
{
  id : 55,
  title : 'Matar Upma',
  category : 'Upma',
  price :80,
  img : './images/item-55.jpeg',
  desc:`Unique flavor from the addition of tamarind and distinctive spices`,
},
{
  id : 56,
  title : 'Vegetable Upma',
  category : 'Upma',
  price :80,
  img : './images/item-56.jpeg',
  desc:`Mixed with a variety of vegetables, seasoned with spices and herbs`,
},
{
  id : 57,
  title : 'Corn Upma',
  category : 'Upma',
  price :90,
  img : './images/item-57.jpeg',
  desc:`Upma made with sweet corn kernels, semolina, and a blend of spices and herbs`,
},
{
  id : 58,
  title : 'Healthy Oats Upma',
  category : 'Upma',
  price :159,
  img : './images/item-58.jpeg',
  desc:`Cooked with olive oil and pink salt. Use premium quality herbs and English veggies`,
},
{
  id : 59,
  title : 'Coconut Upma',
  category : 'Upma',
  price :110,
  img : './images/item-59.jpeg',
  desc:`Semolina is cooked with grated coconut, spices, and often garnished with fresh herbs`,
},
{
  id : 60,
  title : 'Chicken Dum Pot Biryani',
  category : 'Non-veg Biryani',
  price : 249 ,
  img : './images/item-60.jpeg',
  desc : `Biryani is a spiced mixed of meat and rice, traditionally cooked over an open fire. It is combined in different ways with a variety of components to create a number of highly tasty and unique flavor combinations`,
  },  
  {
  id : 61,
  title : 'Chicken Fry Pot Biryani',
  category : 'Non-veg Biryani',
  price :259 ,
  img : './images/item-61.jpeg',
  desc : `Biryani is a spiced mixed of meat and rice, traditionally cooked over an open fire in a clay pot. It is combined in different ways with a variety of components to create a number of highly tasty and unique flavor combinations`,
  },
  {
  id : 62,
  title : 'Chicken Special Pot Biryani [Couple Pack]',
  category : 'Non-veg Biryani',
  price :399 ,
  img : './images/item-62.jpeg',
  desc : `This biryani comes with chicken dum pieces, boneless curry with an egg on the top. Biryani is a spiced mix of meat and rice, traditionally cooked over an open fire in a clay. It is combined in different ways with a variety of components to create a number of highly tasty and unique flavor combinations`,
  },
  {
  id : 63,
  title : 'Chicken Dum Biryani [Single]',
  category : 'Non-veg Biryani',
  price : 179,
  img : './images/item-64.jpeg',
  desc : `A beautifully scented, flavorsome biryani made by marinating and keeping the chicken dum before adding into the masala`,
  },
  {
  id : 64,
  title : 'Chicken Fry Biryani [Single]',
  category : 'Non-veg Biryani',
  price : 209,
  img : './images/item-.jpeg',
  desc : `A beautifully scented, flavorsome biryani made by marinating and frying the chicken before adding into the masala`,
  },  
  {
  id : 65,
  title : 'Chicken Dum Biryani',
  category : 'Non-veg Biryani',
  price :209 ,
  img : './images/item-65.jpeg',
  desc : `Chicken Dum Biryani is a popular Indian dish that consists of marinated chicken cooked with aromatic basmati rice and a blend of spices. The dish is prepared using the dum cooking method, where the ingredients are layered in a pot and cooked over low heat, allowing the flavors to meld together`,
  },
  {
  id : 66,
  title : 'Chicken Fry Biryani',
  category : 'Non-veg Biryani',
  price :219 ,
  img : './images/item-66.jpeg',
  desc : `A beautifully scented, flavorsome biryani made by marinating and frying the chicken before adding into the masala`,
  },
  {
  id : 67,
  title : 'Chicken Joint Biryani [Couple Pack]',
  category : 'Non-veg Biryani',
  price :369 ,
  img : './images/item-67.jpeg',
  desc : `This chicken biryani recipe features succulent, juicy pieces of chicken joints that are cooked in a yogurt marinade and then layered with crispy onions, coriander, mint and basmati rice to give you a dish that the entire family will enjoy`,
  },
  {
  id : 68,
  title : 'Chicken Dum Biryani [Single] with Chicken Joint [1 Piece]',
  category : 'Non-veg Biryani',
  price :329 ,
  img : './images/item-69.jpeg',
  desc : `Chicken Dum Biryani [Single] + Chicken Joint [1 Piece]`,
  },
  {
  id : 69,
  title : 'Hyderabadi Chicken Biryani',
  category : 'Non-veg Biryani',
  price :340 ,
  img : './images/item-69.jpeg',
  desc : `Chicken Dum Biryani is a popular Indian dish that consists of marinated chicken cooked with aromatic basmati rice and a blend of spices`,
  },
  {
  id : 70,
  title : 'Ulavacharu Chicken Biryani',
  category : 'Non-veg Biryani',
  price :405 ,
  img : './images/item-70.jpeg',
  desc : `Ulavacharu Chicken Biryani is a rich and aromatic South Indian dish featuring tender chicken cooked with fragrant basmati rice, spices, and a signature blend of ulavacharu (horse gram curry) for deep flavor`,
  },
  {
  id : 71,
  title : 'Rambo Chicken Kabab Biryani',
  category : 'Non-veg Biryani',
  price :480 ,
  img : './images/item-71.jpeg',
  desc : `Rambo Chicken Kabab Biryani is a hearty and flavorful fusion dish combining spicy, grilled chicken kebabs with fragrant biryani rice for a robust and satisfying meal`,
  }, 
  {
  id : 72,
  title : 'Chicken Kabab Biryani',
  category : 'Non-veg Biryani',
  price :480 ,
  img : './images/item-72.jpeg',
  desc : `Chicken Kabab Biryani is a savory dish where juicy, spiced chicken kebabs are layered with aromatic biryani rice, creating a flavorful and satisfying combination`,
  },
  {
  id : 73,
  title : 'Chicken Tikka Biryani',
  category : 'Non-veg Biryani',
  price :505 ,
  img : './images/item-73.jpeg',
  desc : `Chicken Tikka Biryani features tender, marinated chicken tikka pieces layered with fragrant basmati rice, offering a spicy and flavorful fusion of traditional biryani and grilled chicken`,
  },
  {
  id : 74,
  title : 'Chicken Wings Biryani',
  category : 'Non-veg Biryani',
  price :585,
  img : './images/item-74.jpeg',
  desc : `Chicken Wings Biryani combines crispy, spiced chicken wings with aromatic biryani rice, creating a flavorful and satisfying twist on the classic dish`,
  },
  {
  id : 75,
  title : 'Chicken Chilli Wings Biryani',
  category : 'Non-veg Biryani',
  price :645 ,
  img : './images/item-75.jpeg',
  desc : `Chicken Chilli Wings Biryani blends spicy, tangy chicken wings with fragrant biryani rice, delivering a bold and flavorful fusion of heat and arom`,
  },
  {
  id : 76,
  title : 'Mutton Dum Biryani',
  category : 'Non-veg Biryani',
  price :510 ,
  img : './images/item-76.jpeg',
  desc : `Mutton Dum Biryani is a rich and aromatic dish featuring tender, slow-cooked mutton and fragrant basmati rice, infused with a blend of spices through a slow-steaming process`,
  },
  {
  id : 77,
  title : 'Mutton Fry Biryani',
  category : 'Non-veg Biryani',
  price :575 ,
  img : './images/item-77.jpeg',
  desc : `Mutton Fry Biryani combines spicy, crispy mutton fry with fragrant basmati rice, creating a robust and flavorful fusion dish`,
  },
  {
  id : 78,
  title : 'Special Fish Biryani',
  category : 'Non-veg Biryani',
  price :575 ,
  img : './images/item-78.jpeg',
  desc : `Special Fish Biryani features succulent pieces of spiced fish layered with aromatic basmati rice, offering a unique and flavorful twist on traditional biryani`,
  },
  {
  id : 79,
  title : 'Special Prawns Biryani',
  category : 'Non-veg Biryani',
  price :410 ,
  img : './images/item-79.jpeg',
  desc : `Special Prawns Biryani combines tender, spiced prawns with fragrant basmati rice, delivering a delectable and aromatic seafood twist on the classic biryani`,
  },
  {
  id : 80,
  title : 'Boneless Chicken Biryani',
  category : 'Non-veg Biryani',
  price :465 ,
  img : './images/item-80.jpeg',
  desc : `This blockbuster biryani is slow cooked on charcoal, using the dum technique where the layers of aromatic rice, meat, caramelized onion, and masalas cook in their own steam pressure until rice is fluffy and meat is cooked just to perfection. Served with mirchi ka salan and creamy veggie raita`,
  },
  // {
  // id : 81,
  // title : 'Kaju Paneer Biryani',
  // category : 'Veg Biryani',
  // price :375 ,
  // img : './images/item-81.jpeg',
  // desc : `Kaju Paneer Biryani features creamy paneer cubes and crunchy cashews layered with aromatic basmati rice, creating a rich and flavorful vegetarian twist on the classic dish`,
  // },   
  // {
  // id : 82,
  // title : 'Mushroom 65 Biryani',
  // category : 'Veg Biryani',
  // price :375 ,
  // img : './images/item-82.jpeg',
  // desc : `Mushroom 65 Biryani combines crispy, spicy mushroom pieces with fragrant basmati rice, delivering a flavorful and satisfying vegetarian twist on the classic biryani`,
  // },
  // {
  // id : 83,
  // title : 'Mushroom Biryani',
  // category : 'Veg Biryani',
  // price :330 ,
  // img : './images/item-83.jpeg',
  // desc : `Mushroom Biryani is a savory and aromatic dish featuring tender mushrooms cooked with basmati rice and a blend of spices for a rich, vegetarian delight`,
  // },
  // {
  // id : 84,
  // title : 'Paneer 65 Biryani',
  // category : 'Veg Biryani',
  // price :375 ,
  // img : './images/item-84.jpeg',
  // desc : `Paneer 65 Biryani combines crispy, spiced paneer cubes with aromatic basmati rice, offering a flavorful and satisfying vegetarian take on the classic biryani`,
  // },
  // {
  // id : 85,
  // title : 'Special Veg Handi Biryani',
  // category : 'Veg Biryani',
  // price :390 ,
  // img : './images/item-85.jpeg',
  // desc : `Special Veg Handi Biryani features a medley of fresh vegetables slow-cooked with aromatic basmati rice in a traditional handi, offering a rich and flavorful vegetarian experience`,
  // },
  // {
  // id : 86,
  // title : 'Special Kaju Paneer Biryani',
  // category : 'Veg Biryani',
  // price :408 ,
  // img : './images/item-86.jpeg',
  // desc : `Special Kaju Paneer Biryani features creamy paneer and crunchy cashews layered with aromatic basmati rice, creating a rich and indulgent vegetarian biryani`,
  // },
  // {
  // id : 87,
  // title : 'Ulavacharu Biryani',
  // category : 'Veg Biryani',
  // price :330 ,
  // img : './images/item-87.jpeg',
  // desc : `Ulavacharu Biryani is a flavorful and aromatic dish featuring basmati rice cooked with a unique, spicy horse gram curry (ulavacharu) for a distinctive taste`,
  // },
  // {
  // id : 88,
  // title : 'Veg Pulao',
  // category : 'Veg Biryani',
  // price :215 ,
  // img : './images/item-88.jpeg',
  // desc : `Veg Pulao is a fragrant rice dish cooked with a mix of fresh vegetables and aromatic spices, offering a simple yet flavorful vegetarian option`,
  // },
  // {
  // id : 89,
  // title : 'AIoo 65 Pulao',
  // category : 'Veg Biryani',
  // price :265 ,
  // img : './images/item-89.jpeg',
  // desc : `Aloo 65 Pulao features spiced, crispy potato cubes mixed with aromatic basmati rice, creating a flavorful and satisfying vegetarian rice dish`,
  // },
  // {
  // id : 90,
  // title : 'Special Mixed Veg Pulao',
  // category : 'Veg Biryani',
  // price :355 ,
  // img : './images/item-90.jpeg',
  // desc : `Special Mixed Veg Pulao is a vibrant rice dish packed with a variety of fresh vegetables and aromatic spices, offering a hearty and flavorful vegetarian meal`,
  // },
  // {
  // id : 91,
  // title : 'Special Paneer Pulao',
  // category : 'Veg Biryani',
  // price :385 ,
  // img : './images/item-91.jpeg',
  // desc : `Special Paneer Pulao features tender paneer cubes cooked with aromatic basmati rice and spices, creating a rich and flavorful vegetarian dish`,
  // },
  // {
  // id : 92,
  // title : 'White Rice',
  // category : 'Rice',
  // price :65 ,
  // img : './images/item-92.jpeg',
  // desc : `White Rice is a simple and versatile staple, known for its mild flavor and fluffy texture, often served as a base for various dishes,`
  // },
  // {
  // id : 93,
  // title : 'Curd Rice',
  // category : 'Rice',
  // price :110 ,
  // img : './images/item-93.jpeg',
  // desc : `Curd Rice is a comforting dish of soft rice mixed with creamy yogurt and seasoned with spices, offering a cooling and soothing accompaniment`,
  // },
  // {
  // id : 94,
  // title : 'Sambar Rice',
  // category : 'Rice',
  // price :160 ,
  // img : './images/item-94.jpeg',
  // desc : `Sambar Rice is a hearty and flavorful dish combining rice with a tangy, spiced lentil stew and vegetables, offering a satisfying South Indian meal`,
  // },
  // {
  // id : 95,
  // title : 'Jeera Rice',
  // category : 'Rice',
  // price :200 ,
  // img : './images/item-95.jpeg',
  // desc : `Jeera Rice is a fragrant, spiced rice dish flavored with cumin seeds, offering a simple yet aromatic accompaniment to a variety of dishes`,
  // },
  // {
  // id : 96,
  // title : 'Tomato Curry',
  // category : 'Veg curries',
  // price :210 ,
  // img : './images/item-96.jpeg',
  // desc : `Tomato Curry is a tangy and flavorful dish featuring tomatoes cooked with aromatic spices, creating a rich and savory sauce perfect for pairing with rice or bread`,
  // },
  // {
  // id : 97,
  // title : 'Plain Palak',
  // category : 'Veg curries',
  // price :230 ,
  // img : './images/item-97.jpeg',
  // desc : `Plain Palak is a simple, yet nutritious dish featuring sautéed spinach cooked with mild spices, offering a fresh and healthy vegetarian option`,
  // },
  // {
  // id : 98,
  // title : 'Mix Veg Curry',
  // category : 'Veg curries',
  // price :265 ,
  // img : './images/item-98.jpeg',
  // desc : `Mix Veg Curry is a hearty and colorful dish featuring a variety of vegetables simmered in a flavorful, spiced gravy for a satisfying and nutritious meal`,
  // },
  // {
  // id : 99,
  // title : 'Capsicum Curry',
  // category : 'Veg curries',
  // price :225 ,
  // img : './images/item-99.jpeg',
  // desc : `Capsicum Curry is a flavorful dish with tender bell peppers cooked in a spiced gravy, offering a savory and slightly sweet taste`,
  // },
  // {
  // id : 100,
  // title : 'Kadai Veg',
  // category : 'Veg curries',
  // price :290 ,
  // img : './images/item-100.jpeg',
  // desc : `Kadai Veg is a vibrant and aromatic dish featuring a mix of fresh vegetables cooked with spices and bell peppers in a wok-like "kadai" for a rich and flavorful experience`,
  // },
  // {
  // id : 101,
  // title : 'Plain Palak Paneer Curry',
  // category : 'Veg curries',
  // price :290 ,
  // img : './images/item-101.jpeg',
  // desc : `Plain Palak Paneer Curry is a comforting dish featuring tender paneer cubes simmered in a mild, spiced spinach gravy for a nutritious and creamy vegetarian option`,
  // },
  // {
  // id : 102,
  // title : 'Paneer Butter Masala Curry',
  // category : 'Veg curries',
  // price :290 ,
  // img : './images/item-102.jpeg',
  // desc : `Paneer Butter Masala Curry is a rich and creamy dish featuring paneer cubes in a luscious tomato-based gravy with butter and spices, offering a indulgent vegetarian treat`,
  // },
  // {
  // id : 103,
  // title : 'Veg Patiala Curry',
  // category : 'Veg curries',
  // price :290 ,
  // img : './images/item-103.jpeg',
  // desc : `Veg Patiala Curry is a flavorful and creamy dish featuring a medley of vegetables in a rich, spiced tomato and cream sauce, offering a hearty vegetarian delight`,
  // },
  // {
  // id : 104,
  // title : 'Aloo Capsicum Curry',
  // category : 'Veg curries',
  // price :300 ,
  // img : './images/item-104.jpeg',
  // desc : `Aloo Capsicum Curry is a savory dish featuring tender potatoes and bell peppers cooked together in a spiced gravy, offering a satisfying and flavorful vegetarian option`,
  // },
  // {
  // id : 105,
  // title : ' Methi Chaman Curry',
  // category : 'Veg curries',
  // price :330 ,
  // img : './images/item-105.jpeg',
  // desc : `Methi Chaman Curry is a flavorful dish made with paneer and fenugreek leaves in a spiced, creamy gravy, offering a unique and aromatic vegetarian experience`,
  // },
  // {
  // id : 106,
  // title : ' Mushroom Curry',
  // category : 'Veg curries',
  // price :295 ,
  // img : './images/item-106.jpeg',
  // desc : `Mushroom Curry is a rich and savory dish featuring tender mushrooms cooked in a spiced, flavorful gravy, providing a satisfying vegetarian option`,
  // },
  // {
  //   id : 107,
  //   title : ' Tomato Kaju Curry',
  //   category : 'Veg curries',
  //   price :350 ,
  //   img : './images/item-107.jpeg',
  //   desc : `Tomato Kaju Curry is a rich and tangy Indian dish featuring creamy cashews in a spiced tomato-based sauce`,
  // },
  // {
  //   id : 108,
  //   title : ' Fruit Salad with Ice Cream',
  //   category : 'Ice Cream',
  //   price :79 ,
  //   img : './images/item-108.jpeg',
  //   desc : `A refreshing medley of colorful, juicy fruits topped with creamy, indulgent ice cream for a delightful contrast of flavors and textures`,
  //   },
  //   {
  //   id : 109,
  //   title : 'Vanilla Ice Cream',
  //   category : 'Ice Cream',
  //   price :70 ,
  //   img : './images/item-109.jpeg',
  //   desc : `Creamy and smooth, vanilla ice cream offers a timeless, subtly sweet flavor that delights with its rich simplicity`,
  //   },
  //   {
  //   id : 110,
  //   title : 'Pista Ice Cream',
  //   category : 'Ice Cream',
  //   price :80 ,
  //   img : './images/item-110.jpeg',
  //   desc : `Pista ice cream combines the rich, nutty flavor of pistachios with a creamy texture for a sophisticated and indulgent treat`,
  //   },
  //   {
  //   id : 111,
  //   title : 'Butterscotch Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-111.jpeg',
  //   desc : `Butterscotch flavoured ice cream with cashew praline + walnut praline`,
  //   },
  //   {
  //   id : 112,
  //   title : ' Sea Salt Caramel Pecan Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-112.jpeg',
  //   desc : `Caramel and pecan serve up a treat that is part salty, part nutty`,
  //   },
  //   {
  //   id : 113,
  //   title : ' Tiramisu Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-113.jpeg',
  //   desc : `Experience a jolt of flavor as tiramisu and coffee come together to make you to a world of indulgence`,
  //   },
  //   {
  //   id : 114,
  //   title : 'Virgin Mojito',
  //   category : ' Mojito ',
  //   price : 70,
  //   img : './images/item-114.jpeg',
  //   desc : `A virgin mojito is a refreshing, non-alcoholic blend of zesty lime, fresh mint, and sparkling soda, perfect for a cool, invigorating drink`,
  //   },
    
  //   {
  //   id : 115,
  //   title : ' Blue Curacao Mocktail',
  //   category : 'Mocktail',
  //   price : 70,
  //   img : './images/item-115.jpeg',
  //   desc : `A Blue Curacao mocktail is a vibrant, non-alcoholic drink featuring the tropical, citrusy flavors of blue Curacao syrup and a splash of refreshing soda`,
  //   },
    
  //   {
  //   id : 116,
  //   title : ' Vanilla Mocktail ',
  //   category : 'Mocktail',
  //   price :70,
  //   img : './images/item-116.jpeg',
  //   desc : `A vanilla mocktail is a smooth, non-alcoholic blend that combines the creamy sweetness of vanilla with refreshing citrus or fruity notes`,
  //   },
  //   {
  //   id : 117,
  //   title : ' Polo Mocktail',
  //   category : 'Mocktail',
  //   price :70 ,
  //   img : './images/item-117.jpeg',
  //   desc : `A Polo mocktail is a crisp, non-alcoholic beverage with a cool, minty flavor and a refreshing, effervescent finish`,
  //   },
  //   {
  //   id : 118,
  //   title : ' Almond Crunch Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-118.jpeg',
  //   desc : `Crunchy almonds with subtle vanilla `,
  //   },
  //   {
  //   id : 119,
  //   title : 'Alphonso Mango Ice Cream',
  //   category : 'Ice Cream',
  //   price : 119,
  //   img : './images/item-119.jpeg',
  //   desc : `Mango flavoured ice cream with chunks of mango`,
  //   },
    
  //   {
  //   id : 120,
  //   title : 'Bean Vanilla Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-120.jpeg',
  //   desc : `Natural vanilla flavoured ice cream with vanilla bean powder`,
  //   },
  //   {
  //   id : 121,
  //   title : ' Belgian Chocolate Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-121.jpeg',
  //   desc : `Belgian cocoa powder based ice cream`,
  //   },
  //   {
  //   id : 122,
  //   title : ' Black Forest Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-122.jpeg',
  //   desc : `Experience a side of Blackforest you've never known before`,
  //   },
  //   {
  //   id : 123,
  //   title : 'Blackberry Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-123.jpeg',
  //   desc : `The dark delicious creamy side of blackberry`,
  //   },
  //   {
  //   id : 124,
  //   title : 'Blueberry Cheesecake Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-124.jpeg',
  //   desc : `Surrender to the charms of blueberry and cheese`,
  //   },
  //   {
  //   id : 125,
  //   title : 'Butterscotch Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-125.jpeg',
  //   desc : `Butterscotch flavoured ice cream with cashew praline + walnut praline`,
  //   },
  //   {
  //   id : 126,
  //   title : 'Mango Raspberry Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-126.jpeg',
  //   desc : `A heady blend of mango and raspberry flavored ice cream to take you on a journey to fruit and berry land`,
  //   },
    
  //   {
  //   id : 127,
  //   title : 'Pistachio Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-127.jpeg',
  //   desc : `Pistachios rich in flavour, and with that unmistakable Californian swagger`,
  //   },
  //   {
  //   id : 128,
  //   title : 'Chocolate Overload Ice cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-128.jpeg',
  //   desc : `Deep and rich chocolate flavour that truly defines indulgence`,
  //   },
  //   {
  //   id : 129,
  //   title : 'Cotton Candy Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-129.jpeg',
  //   desc : `This is what sweet memories are made off`,
  //   },
  //   {
  //   id : 130,
  //   title : 'Fruit Bonanza Ice Cream',
  //   category : 'Ice Cream',
  //   price :119 ,
  //   img : './images/item-130.jpeg',
  //   desc : `Vanilla flavoured ice cream with fig, blackcurrant, pineapple, raisins, cashews & tutty fruity `,
  //   },
  //   {
  //   id : 131,
  //   title : 'Fresh Strawberry Milkshake',
  //   category : 'Milk shakes',
  //   price :120 ,
  //   img : './images/item-131.jpeg',
  //   desc : `A fresh strawberry milkshake blends creamy vanilla ice cream with juicy strawberries for a sweet, fruity, and indulgent treat`,
  //   },
    
  //   {
  //   id : 132,
  //   title : 'Cold Coffee',
  //   category : 'Milk shakes',
  //   price :130 ,
  //   img : './images/item-132.jpeg',
  //   desc : `Cold coffee is a chilled, invigorating brew with a rich, bold flavor and a smooth, refreshing finish`,
  //   },
  //   {
  //   id : 133,
  //   title : 'Chocolate Milkshake',
  //   category : 'Milk shakes',
  //   price :130 ,
  //   img : './images/item-133.jpeg',
  //   desc : `A chocolate milkshake is a creamy, indulgent blend of rich chocolate and smooth vanilla ice cream, delivering a sweet, satisfying treat`,
  //   },
  //   {
  //   id : 134,
  //   title : 'Butterscotch Milkshake',
  //   category : 'Milk shakes',
  //   price :120 ,
  //   img : './images/item-134.jpeg',
  //   desc : `A butterscotch milkshake combines creamy vanilla ice cream with buttery, caramelized butterscotch for a rich, sweet, and decadent flavor experience`,
  //   },
  //   {
  //   id : 135,
  //   title : 'Blackcurrant Milkshake',
  //   category : 'Milk shakes',
  //   price :140,
  //   img : './images/item-135.jpeg',
  //   desc : `A blackcurrant milkshake features a creamy blend of tangy blackcurrants and smooth vanilla ice cream for a uniquely fruity and refreshing treat`,
  //   },
  //   {
  //   id : 136,
  //   title : 'Carmel Nuts Milkshake',
  //   category : 'Milk shakes',
  //   price :145 ,
  //   img : './images/item-136.jpeg',
  //   desc : `A caramel nuts milkshake blends creamy vanilla ice cream with rich caramel and crunchy nuts for a sweet and satisfying texture`,
  //   },
  //   {
  //   id : 137,
  //   title : 'KitKat Milkshake',
  //   category : 'Milk shakes',
  //   price :160 ,
  //   img : './images/item-137.jpeg',
  //   desc : `A KitKat milkshake combines creamy vanilla ice cream with crushed KitKat bars for a rich, chocolatey treat with delightful crispy bites`,
  //   },
  //   {
  //   id : 138,
  //   title : 'Litchi Milkshake',
  //   category : 'Milk shakes',
  //   price :150 ,
  //   img : './images/item-138.jpeg',
  //   desc : `A litchi milkshake offers a creamy, exotic blend of sweet litchi fruit and smooth vanilla ice cream for a refreshing and unique flavor experience`,
  //   },
  //   {
  //   id : 139,
  //   title : 'Special Badam Milk',
  //   category : 'Milk shakes',
  //   price :65 ,
  //   img : './images/item-139.jpeg',
  //   desc : `Special badam milk is a rich, aromatic beverage made with creamy milk and finely ground almonds, infused with cardamom and saffron for a luxurious, nutty treat`,
  //   },










];
export default menu;